apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: null
  name: jenkins-ceph-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  rbd:
    fsType: ext4
    image: jenkins
    monitors:
    - ceph-mon01.osdec.gov.my:6789
    - ceph-mon02.osdec.gov.my:6789
    - ceph-mon03.osdec.gov.my:6789
    pool: rbd
    secretRef:
      name: ceph-secret
    user: admin
status: {}
