apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: null
  name: jenkins-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /nfsshare/jenkins
    server: openshift-nfsshare.osdec.gov.my
  persistentVolumeReclaimPolicy: Retain
status: {}
