apiVersion: v1
kind: Template
metadata:
  name: generic-db-secret-template
parameters:
- name: SECRET_NAME
  description: Secret Name
  required: true
- description: The database URL/Connection String defined in this template.
  displayName: Database Url
  name: DB_URL
  required: true
- description: The username of database defined in this template.
  displayName: Database Username
  name: DB_USERNAME
  required: true
- description: The password of database defined in this template.
  displayName: Database Password
  name: DB_PASSWORD
  required: true
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${SECRET_NAME}
  type: Opaque 
  stringData: 
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}