apiVersion: v1
kind: Template
metadata:
  name: network-policy-allow-namespace-template
  annotations:
    openshift.io/display-name: Network Policy Allow Same Namespace
    description: |-
      This template showcases network policy to allow internal network in same namespace
      and allow traffic from specific namespace
    tags: 
parameters:
- name: TARGET_NAMESPACE
  description: Target Namespace
  required: true
objects:
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: allow-same-namespace-${TARGET_NAMESPACE} 
  spec:
    podSelector:
    ingress:
    - from:
      - podSelector: {}
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: allow-from-default-namespace-to-${TARGET_NAMESPACE} 
  spec:
    podSelector:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: default