kind: Template
apiVersion: v1
metadata:
  annotations:
    description: The SonarQube OpenShift template
    tags: instant-app,sonarqube
  name: sonarqube
message: "Login to SonarQube with the default admin user: admin/admin"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${SONARQUBE_SVC_NAME}
    labels:
      app: ${SONARQUBE_SVC_NAME}
  spec:
    ports:
    - name: sonarqube
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: ${SONARQUBE_SVC_NAME}
      deploymentconfig: ${SONARQUBE_SVC_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for SonarQube's http service.
    name: ${SONARQUBE_SVC_NAME}
    labels:
      app: ${SONARQUBE_SVC_NAME}
  spec:
    to:
      kind: Service
      name: ${SONARQUBE_SVC_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${SONARQUBE_SVC_NAME}
      deploymentconfig: ${SONARQUBE_SVC_NAME}
    name: ${SONARQUBE_SVC_NAME}
  spec:
    replicas: 1
    selector:
      app: ${SONARQUBE_SVC_NAME}
      deploymentconfig: ${SONARQUBE_SVC_NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/container.sonarqube.image.entrypoint: '["./bin/run.sh"]'
        creationTimestamp: null
        labels:
          app: ${SONARQUBE_SVC_NAME}
          deploymentconfig: ${SONARQUBE_SVC_NAME}
      spec:
        containers:
        - image: ' '
          imagePullPolicy: IfNotPresent
          name: ${SONARQUBE_SVC_NAME}
          ports:
          - containerPort: 9000
            protocol: TCP
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            httpGet:
              port: 9000
              path: /
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            httpGet:
              port: 9000
              path: /
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: ${SONAR_MAX_MEMORY}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/sonarqube/data
            name: ${SONARQUBE_SVC_NAME}-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: ${SONARQUBE_SVC_NAME}-data
          persistentVolumeClaim:
            claimName: sonarqube-data
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${SONARQUBE_SVC_NAME}
        from:
          kind: ImageStreamTag
          name: ${SONARQUBE_IMAGE}:${SONARQUBE_VERSION}
          namespace: ${SONARQUBE_NAMESPACE}
      type: ImageChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${SONARQUBE_SVC_NAME}-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${SONAR_VOLUME_CAPACITY}
parameters:
- displayName: SonarQube Service Name
  value: "sonarqube"
  name: SONARQUBE_SVC_NAME
  required: true
- displayName: SonarQube Image Namespace
  value: "openshift"
  name: SONARQUBE_NAMESPACE
  required: true
- displayName: SonarQube Image Namespace
  value: "sonarqube"
  name: SONARQUBE_IMAGE
  required: true
- displayName: SonarQube version
  value: "latest"
  name: SONARQUBE_VERSION
  required: true
- description: Volume space available for SonarQube
  displayName: SonarQube Volume Capacity
  name: SONAR_VOLUME_CAPACITY
  required: true
  value: 1Gi
- displayName: SonarQube Max Memory
  name: SONAR_MAX_MEMORY
  required: true
  value: 2Gi